### ISSUE TITLE
April Task List

### ISSUE THREAD

**Issue by emily-plummer** [donut-js/donut-js.github.io#21]
## Next few weeks
- [ ] ~~Order Donut Balloons - @emily-plummer~~
- [x] Donut stickers for name tags Treehouse - @matthewmcvickar 
- [x] Set up email account - @emily-plummer
- [ ] Research Laser engraved donut things - @samplifylife
- [x] Tweet things (ask @emily-plummer for our Buffer acct details)
- [x] Add sponsors to website -
- [x] Add new talk submission form to website -
- [x] get karafun

## Week of
- [x] Write up loose scripts for opening remarks - group https://paper.dropbox.com/doc/gQmgor8XuokiEZj5F7MLp
- [ ] Chat about handling CoC violations if they come up - group
- [x] Write day before email (make sure to include sponsor logos) - 
- [x] Contact Coco Donuts (ideally more than a week before) -
- [x] Create Slack group for attendees -

## Day of
- [ ] call back to eden in the morning & reserve 5 donuts
- [ ] Record the talks - @maxogden 
- [ ] Bring extra benches - @samplifylife
- [ ] Pick up donuts - Emily's MOM lol ❤️ 
- [ ] Help with checkin at the door - @matthewmcvickar @jlord
- [ ] Bring lightening port converters -
- [ ] need laptop for karafun (and for this laptop to have karafun downloaded!)
- [ ] swag table
- [ ] plates for donuts?
- [ ] sign for vegan donuts (11 people requested, we got 12)
- [ ] 1/8" extension cable (from mixer area to camera) (@obensource)
- [ ] power extension cable (from  mixer area/the wall under the projector to camera) (@obensource)
- [ ] tape to tape down the cables (@obensource)
- [ ] camera tripod (@emily-plummer)

## After event
- [ ] Send feedback email night of -
- [ ] Have recap meeting a few days later - group

**Comment by matthewmcvickar** [comment]
@emily-plummer I would love to help with check-in at the door.

**Comment by matthewmcvickar** [comment]
@emily-plummer Also, we can remove hole-punchers from this list, as the stickers will come pre-punched!

**Comment by emily-plummer** [comment]
Things to cover in opening remarks:
- code of conduct
- sponsors
- ask people to submit cfp/performances
- Slack group
- if you're interested in being contacted by any of our sponsors
- people talk to people
- may tickets

**Comment by maxogden** [comment]
@obensource i added items for you in the checklist above

**Comment by obensource** [comment]
@maxogden great, thanks! :D

**Comment by obensource** [comment]
Hrm... I have not the privileges to check the boxes above so I'll check-in here: 

* Picked up the PA speakers, Wireless Headset mics, cables.
* Have the rest of the sound equipment ready (amp, line-mixer, cables, etc)
@maxogden:
* Have the power extension chord
* Have the gaff tape to tape cables down
* Most likely have the long 1/8" stereo cable for you at home, but if not will pick up tomorrow.

**Comment by obensource** [comment]
Something that would be nice: would someone be able to download apogee duet 2 drivers, and Audacity so we can have a standalone computer dedicated to recording, if not I'm going to have to try something that is theoretically possible but maybe unpredictable which I've never done before: have a high-sampled audio stream recording in one application while generating/processing a ton of audio streams in another. 😬

Please let me know if anyone can let me use their machine for recording. Thanks all!

**Comment by obensource** [comment]
Looks like I can use Sam Syder's machine. 👍

**Comment by matthewmcvickar** [comment]
@obensource If Sam Snyder's machine falls through, you can use mine; it's already got Apogee drivers and Audacity on it.
